# This is a basic workflow to help you get started with Actions
name: CD

# Controls when the action will run.
on:
  push:
    branches:  [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: actions/checkout@v2
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.HOST}}

      - name: Install PM2 locally
        run: |
          npm i -g pm2

      - name: Create env file
        run: |
          touch .env
          echo SERVER_PORT=${{ secrets.PORT }} >> .env
          echo SERVER_IP=${{ secrets.HOST }} >> .env
          echo SERVER_USER=${{ secrets.USERNAME }} >> .env
          echo GIT_TOKEN=${{ secrets.GIT_TOKEN }} >> .env

      - name: Deploy with PM2
        run: |
          env $(cat .env | grep -v \"#\" | xargs) pm2 deploy ecosystem.config.js staging
