# This is a basic workflow to help you get started with Actions
name: CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types:
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/Apps/
            wget https://api.github.com/repos/Voikyrioh/vk-web-gp-cube/tarball/refs/heads/${{ github.event.release.tag_name }}
            mkdir web-gpcube-${{ github.event.release.tag_name }}/
            tar -xvzf ${{ github.event.release.tag_name }} -C web-gpcube-${{ github.event.release.tag_name }}/ --strip-components=1
            cd ./web-gpcube-${{ github.event.release.tag_name }}/
            npm i --omit=dev
            npm run build-production
            cp -r dist/* /var/www/web-gpcube.voikyrioh.fr/
            cd ../
            rm -r ./web-gpcube-${{ github.event.release.tag_name }}
            rm ./${{ github.event.release.tag_name }}
