# This is a basic workflow to help you get started with Actions
name: Deploy to dev

# Controls when the action will run.
on:
  workflow_dispatch


jobs:
  deploy:
    name: Deploiement de ${{ github.ref_name }} sur DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.DEV_HOST}}

      - name: Install PM2 locally
        run: |
          npm i -g pm2

      - name: Create env file
        run: |
          touch .env
          echo SERVER_PORT=${{ secrets.DEV_PORT }} >> .env
          echo SERVER_IP=${{ secrets.DEV_HOST }} >> .env
          echo SERVER_USER=${{ secrets.DEV_USERNAME }} >> .env
          echo GIT_TOKEN=${{ secrets.GIT_TOKEN }} >> .env
          echo WEB_CUBE_PATH=${{ secrets.PROJECT_PATH_DEV }} >> .env
          echo BRANCH=${{ github.ref_name }} >> .env

      - name: Deploy with PM2
        run: |
          env $(cat .env | grep -v \"#\" | xargs) pm2 deploy ecosystem.config.cjs development
